

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <title>Watermim Project</title>
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <link href="default.css" rel="stylesheet" type="text/css" />
    <link href="layout.css" rel="stylesheet" type="text/css" />
    <script type="text/javascript" src="jquery-1.3.2.min.js"></script>
    <script src="jquery.cycle.lite.min.js" type="text/javascript"></script>
   <script type="text/javascript">
       $(function() {
       $('#splash').cycle({ speed: 6000 });
         
       });
    </script>
<meta name="WebsiteSpark" content="fKp42PF8Yw" />

</head>
<body>
    <form name="aspnetForm" method="post" action="default.aspx" id="aspnetForm">
<input type="hidden" name="__VIEWSTATE" id="__VIEWSTATE" value="/wEPDwULLTEwMDUyNjYzMjhkGAEFHl9fQ29udHJvbHNSZXF1aXJlUG9zdEJhY2tLZXlfXxYCBRhjdGwwMCRMb2dpblN0YXR1czEkY3RsMDEFGGN0bDAwJExvZ2luU3RhdHVzMSRjdGwwM3l55rNdFe0RFqUTCVXo8V2ROsTS" />

<input type="hidden" name="__VIEWSTATEGENERATOR" id="__VIEWSTATEGENERATOR" value="0343F652" />
    <div id="page">
        <div id="header">
            <div id="logo">
                <img src="images/logo.PNG" />
            </div>
            <div id="login">
                <a id="ctl00_LoginStatus1" href="javascript:__doPostBack('ctl00$LoginStatus1$ctl02','')">Login</a>
            </div>
        </div>
        <div style="clear: both;" />
        <div id="mainmenu">
            <ul>
                <li><a href="default.aspx" title="Warermim homepage">Homepage</a></li>
                <li><a href="objectives.aspx" title="Project Objectives">Project Objectives</a></li>
                <li><a href="Partners.aspx" title="Partners">Project Partners</a></li>
                <li><a href="EU.aspx" title="Partners">EC Contacts</a></li>
                <li><a href="activities.aspx" title="News & Events">News & Events</a></li>
                <li><a href="publications.aspx" title="Publications">Publications</a></li>
                <li><a href="login.aspx" title="Members Area">Members Area</a></li>
            </ul>
        </div>
        <div id="splash">
            <img src="images/water.png" />
            <img src="images/imprinting.png" />
           
        </div>
        <div style="clear: both" />
        <div id="container">
            
    <div id="content">
        <h1>
            Water Treatment by Molecularly Imprinted Materials</h1>
        <p>
            <img style="margin: 10px; float: right;" title="membrane2_.png" src="http://lpre.cperi.certh.gr/watermim/images/membrane2_.png"
                alt="membrane2_.png" height="233" width="313">The WATERMIM project is focused
            on the advancement and optimization of the MIP technology in order to produce functional
            materials with well-defined morphologies with respect to pore structure and selectivity
            for water treatment applications. The project aims at the elimination of the random
            distribution and the uneven accessibility of receptor sites in the volume of the
            imprinted material that is crucial for its performance.
        </p>
        <p>
            Such novel materials will immediately gain practical relevance, especially, due
            to their increased selectivity and superior stability under long and harsh technical
            conditions. The simultaneous optimization of the imprinting efficiency, polymer
            membrane morphology and separation conditions will enable the development of a truly
            molecular selective water purification process, based on affinity interactions that
            would have a large application impact on the water treatment industry.
        </p>
        <p>
            All types of synthetic organic compounds (i.e., triazines, pharmaceutical compounds
            and endocrine disruptors) are considered target compounds in the WATERMIM project.</p>
        <p><img alt="FP7" src="images/FP7-gen-RGB.jpg" style="float:right ; margin:10px;"><img alt="FP7" src="images/eu.png" style="float:right ; margin:10px;">
            <em>The project is funded by the European Commission in the 7th Framework Programme
                under grant agreement number 226524</em>
        </p>
        <p>
            <em>Project duration 1 May 2009 - 30&nbsp;April 2012</em></p>
        <p>
            <em>WATERMIM&nbsp;is partner in the Nano4water cluster </em>
        </p>
        <p> 
            <em>More information on the Nano4water cluster can be found on the website </em>
            <a href="http://www.nano4water.eu/"><em>www.nano4water.eu</em></a> 
        </p>
    </div>

        </div>
        <div id="footer">
            <p id="links">
                &copy; 2010 Watermim Project. All rights reserved .</p>
            <p id="copyright">
                <a href="mailto:watermim@cperi.certh.gr">Contact us</a> | <a href="http://www.nano4water.eu/">
                    Nano4water.eu</a>
            </p>
        </div>
    </div>
    </form>
</body>
</html>
