<!DOCTYPE HTML>
<html lang="en-US">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
<title>Stimulate - Introduction</title>
<link rel="shortcut icon" href="style/images/favicon.png"/>
<link rel="stylesheet" type="text/css" href="style.css" media="all" />
<link rel="stylesheet" type="text/css" href="style/css/view.css" media="all" />
<link rel="stylesheet" type="text/css" href="style/type/marketdeco.css" media="all" />
<link rel="stylesheet" type="text/css" href="style/type/merriweather.css" media="all" />
<link rel="stylesheet" type="text/css" href="style/css/queries.css" media="all" />
<!--[if IE 8]>
<link rel="stylesheet" type="text/css" href="style/css/ie8.css" media="all" />
<![endif]-->
<!--[if IE 9]>
<link rel="stylesheet" type="text/css" href="style/css/ie9.css" media="all" />
<![endif]-->
<script type="text/javascript" src="style/js/jquery-1.7.1.min.js"></script>
<script type="text/javascript" src="style/js/ddsmoothmenu.js"></script>
<script type="text/javascript" src="style/js/html5.js"></script>
<script type="text/javascript" src="style/js/jquery.fitvids.js"></script>
<script type="text/javascript" src="style/js/selectnav.js"></script>
<script type="text/javascript" src="style/js/twitter.min.js"></script>
<style type="text/css">
#just {
	text-align: justify;
}
#page #wrapper #main #primary #content .post.hentry.format-image .entry-header div div p {
	text-align: justify;
}
#page #wrapper #main #primary #content .post.hentry.format-image .entry-header div div .entry-title strong {
	color: #FF0000;
}
#page #wrapper #main #primary #content .post.hentry.format-image .entry-header div div .entry-title strong {
	text-align: justify;
}
#page #wrapper #main #primary #content .post.hentry.format-image .entry-header div div .entry-title strong {
	text-align: center;
}
</style>
</head>

<body>
<div id="page" class="hfeed">
<div id="wrapper">
<header id="branding" role="banner">
  <h1 id="site-title"><strong>Stimulate
      <br>
  </strong></h1>
  <nav id="access" class="access" role="navigation">
        <div id="menu" class="menu">
        	<ul id="tiny">
				<li><a href="index.html">Introduction</a></li>
				<li><a href="project.html">The Project</a></li>
                <li><a href="deliverables.html">Deliverables</a></li>
                <li><a href="partners.html">Partners</a></li>
                <li><a href="members/">Members Only</a></li>
				<li><a href="contact.html">Contact</a></li>
		  </ul>
		</div>
		<div class="triangle-l"></div>
		<div class="triangle-r"></div>
  </nav>
  <!-- #access --> 
</header>
<!-- #branding -->

<div id="main">

<div id="primary">
  <div id="content" role="main">
  
  <div class="intro"><strong>STIMULATE - INTRODUCTION</strong></div>
  <article class="post hentry format-image">
    <header class="entry-header">
      <div>
        <div>
          <p class="entry-title"><u><strong>Visit the official webportal of STIMULATE        project here:</strong></u> </p>
          <p class="entry-title"><u><a href="http://www.materialsfuture.eu"><strong>www.materialsfuture.eu</strong></a></u><a href="http://www.materialsfuture.eu"><strong></strong></a></p>
          <p class="entry-title">&nbsp;</p>
          <p class="entry-title">Stimulating the public attitude towards Advanced  Materials<strong><br>
            </strong><br>
            <em>Acronym:</em> STIMULATE</p>
<p class="entry-title"><br>
  <em>Type of funding scheme:</em> Coordination and support actions  (Supporting)<br>
  <br>
  <em>Work programme topics:</em> FP7-NMP-2013-CSA-7</p>
<p class="entry-title"><br>
  NMP 2.3-1 Advanced materials – our allies  for a sustainable future<br>
</p>
<p>&nbsp;</p>
<p>More than seventy percent of all technical innovations today depend  directly or indirectly on the development of advanced materials. Advanced materials have been identified as one of the 6 Key  Enabling Technologies, of systemic relevance that 
feed many different cooperating business sectors. Exactly because of the  complicated nature of their role as technology enablers, advanced materials many times miss the general public&rsquo;s  attention. People tend to underestimate the importance of advanced materials, since they are mostly focused on the final  consuming products, instead of appreciating the underlying materials technologies.<br>
<br>
In order to uncover this hidden role, we will create a cross-platform media  approach, integrating onto a web portal, online educational resources, a web-based serious game and a character-led  documentary film that will be translated in all the official EU languages. </p>
<p>To achieve this task we involve a multidisciplinary team of experts (in  advanced materials, documentary filming, game based education, e-learning, scientific journalism etc) that are combining  their expertise in order to create a coherent set of media products.</p>
<p>The educational, &ldquo;Serious Game&rdquo;, will be targeted towards teenagers  (between 14 and 17 years old) while the character-led documentary will be targeted towards the general public and especially  the younger people. Overlapping scientific content and cross-references between the two will link them and promote their  distribution.</p>
<p>We plan to introduce people to a world of invention and innovation. We  aim to give our audience a clear vision for a sustainable future, based on Knowledge, Development and Innovation, with  advanced materials at its core. We will present all the sides of the materials community to the general public, including  research, development and manufacturing, highlighting the role of materials innovation in the struggle of the European  societies to face the current economic and environmental challenges.</p>
        </div>
        <div class="entry-header">
          <p class="note-box">- We will create a cross-platform approach, integrating onto  a web portal, online educational  resources, a web-based serious game and a character-led documentary film. </p>
          <p class="note-box">- The serious game and the  documentary are designed so that they can also stand alone in the media markets  i.e. they will be able to be used also independently. </p>
        </div>
        <div class="note-box">- The educational, &ldquo;Serious Game&rdquo;, will be specifically  targeted towards teenagers (esp. boys and  girls between 14 and 17 years old). </div>
        <div></div>
        <div class="note-box">- The character-led  documentary will be targeted towards  the general public and especially the younger people, with the aim to introduce  them to this field and (in the medium to long term) to attract them to it.        </div>
        <div class="note-box">- Overlapping scientific content and cross-references between the two  stand-alone media products (i.e. the Serious Game and the Documentary) will  link them and promote their dissemination. </div>
        <p align="center">&nbsp;</p></div></header>
    <!-- .entry-content -->
</article>
  <!-- end article -->
  
  
  <!-- begin article -->
  <!-- end article -->
  
  <!-- begin article -->
  <!-- end article -->
  
  <!-- begin article -->
  <!-- end article -->
  
  <!-- begin article -->
  <!-- end article -->
  
  
  <!-- begin article -->
  <!-- end article -->
  
  
  <!-- begin article -->
  <!-- end article -->
  
  <!-- begin article -->
  <!-- end article -->
  
  <!-- begin article -->
  <!-- end article -->
  
  
  		
		<!-- Begin Page-navi -->    <!-- End Page-navi -->
  
  </div><!-- #content -->
</div><!-- #primary -->


</div><!-- #main -->

	<footer id="colophon" role="contentinfo"><!-- #supplementary -->
	  <div id="site-generator"></div>

	</footer><!-- #colophon -->
	</div><!-- #wrapper -->
</div><!-- #page -->

<script type="text/javascript" src="style/js/scripts.js"></script>
</body>
</html>