{"original_uri":"http://comse.chemeng.ntua.gr/amcos/",
"timegate_uri":"http://timetravel.mementoweb.org/timegate/http://comse.chemeng.ntua.gr/amcos/",
"mementos": {
"list": [
{"datetime":"2013-04-18T11:36:31Z",
"uri":"http://web.archive.org/web/20130418113631/http://comse.chemeng.ntua.gr/amcos"
},
{"datetime":"2013-04-18T11:36:31Z",
"uri":"http://web.archive.org/web/20130418113631/http://comse.chemeng.ntua.gr/amcos/"
},
{"datetime":"2013-04-22T01:49:24Z",
"uri":"http://web.archive.org/web/20130422014924/http://comse.chemeng.ntua.gr/amcos/"
},
{"datetime":"2013-05-19T05:31:01Z",
"uri":"http://web.archive.org/web/20130519053101/http://comse.chemeng.ntua.gr/amcos"
},
{"datetime":"2013-05-19T05:31:01Z",
"uri":"http://web.archive.org/web/20130519053101/http://comse.chemeng.ntua.gr/amcos/"
},
{"datetime":"2013-06-25T16:39:19Z",
"uri":"http://web.archive.org/web/20130625163919/http://comse.chemeng.ntua.gr/amcos"
},
{"datetime":"2013-06-25T16:39:19Z",
"uri":"http://web.archive.org/web/20130625163919/http://comse.chemeng.ntua.gr/amcos/"
}
]
 },"timemap_uri": {
"json_format": "http://labs.mementoweb.org/timemap/json/1/http://comse.chemeng.ntua.gr/amcos/"}
 }