{"original_uri":"http://inflacare.imbb.forth.gr/",
"timegate_uri":"http://timetravel.mementoweb.org/timegate/http://inflacare.imbb.forth.gr/",
"mementos": {
"list": [
{"datetime":"2011-08-18T12:47:58Z",
"uri":"http://web.archive.org/web/20110818124758/http://inflacare.imbb.forth.gr/"
},
{"datetime":"2011-08-18T12:52:34Z",
"uri":"http://web.archive.org/web/20110818125234/http://inflacare.imbb.forth.gr/"
},
{"datetime":"2011-09-19T13:34:28Z",
"uri":"http://web.archive.org/web/20110919133428/http://inflacare.imbb.forth.gr/"
},
{"datetime":"2013-01-13T00:57:34Z",
"uri":"http://web.archive.org/web/20130113005734/http://inflacare.imbb.forth.gr/"
},
{"datetime":"2013-01-22T03:59:24Z",
"uri":"http://web.archive.org/web/20130122035924/http://inflacare.imbb.forth.gr/"
},
{"datetime":"2013-09-13T04:09:24Z",
"uri":"http://web.archive.org/web/20130913040924/http://inflacare.imbb.forth.gr/"
},
{"datetime":"2013-09-21T12:00:48Z",
"uri":"http://web.archive.org/web/20130921120048/http://inflacare.imbb.forth.gr/"
},
{"datetime":"2013-10-01T23:22:48Z",
"uri":"http://web.archive.org/web/20131001232248/http://inflacare.imbb.forth.gr/"
},
{"datetime":"2013-10-11T10:02:22Z",
"uri":"http://web.archive.org/web/20131011100222/http://inflacare.imbb.forth.gr/"
},
{"datetime":"2014-09-26T02:18:49Z",
"uri":"http://web.archive.org/web/20140926021849/http://inflacare.imbb.forth.gr/"
},
{"datetime":"2015-06-05T07:45:50Z",
"uri":"http://web.archive.org/web/20150605074550/http://inflacare.imbb.forth.gr/"
},
{"datetime":"2015-09-05T04:52:49Z",
"uri":"http://web.archive.org/web/20150905045249/http://inflacare.imbb.forth.gr/"
},
{"datetime":"2016-03-06T03:29:22Z",
"uri":"http://web.archive.org/web/20160306032922/http://inflacare.imbb.forth.gr/"
}
]
 },"timemap_uri": {
"json_format": "http://labs.mementoweb.org/timemap/json/1/http://inflacare.imbb.forth.gr/"}
 }