{"original_uri":"http://lobos.bordersurveillance.security-copernicus.eu.185-4-133-10.reseller14.grserver.gr/",
"timegate_uri":"http://timetravel.mementoweb.org/timegate/http://lobos.bordersurveillance.security-copernicus.eu.185-4-133-10.reseller14.grserver.gr/",
"mementos": {
"list": [
{"datetime":"2013-09-11T06:48:42Z",
"uri":"http://web.archive.org/web/20130911064842/http://lobos.bordersurveillance.security-copernicus.eu.185-4-133-10.reseller14.grserver.gr"
}
]
 },"timemap_uri": {
"json_format": "http://labs.mementoweb.org/timemap/json/1/http://lobos.bordersurveillance.security-copernicus.eu.185-4-133-10.reseller14.grserver.gr/"}
 }