{"original_uri":"http://www.eng.auth.gr/mattas/teampest/",
"timegate_uri":"http://timetravel.mementoweb.org/timegate/http://www.eng.auth.gr/mattas/teampest/",
"mementos": {
"list": [
{"datetime":"2011-03-13T03:25:17Z",
"uri":"http://web.archive.org/web/20110313032517/http://www.eng.auth.gr/mattas/teampest"
}
]
 },"timemap_uri": {
"json_format": "http://labs.mementoweb.org/timemap/json/1/http://www.eng.auth.gr/mattas/teampest/"}
 }