{"original_uri":"http://bind.upatras.gr/",
"timegate_uri":"http://timetravel.mementoweb.org/timegate/http://bind.upatras.gr/",
"mementos": {
"list": [
{"datetime":"2008-06-04T11:10:29Z",
"uri":"http://web.archive.org/web/20080604111029/http://bind.upatras.gr/"
},
{"datetime":"2010-09-26T11:51:15Z",
"uri":"http://web.archive.org/web/20100926115115/http://bind.upatras.gr/"
},
{"datetime":"2010-12-12T19:40:29Z",
"uri":"http://web.archive.org/web/20101212194029/http://bind.upatras.gr/?"
},
{"datetime":"2011-10-11T16:42:48Z",
"uri":"http://web.archive.org/web/20111011164248/http://www.bind.upatras.gr/"
},
{"datetime":"2011-11-11T02:10:45Z",
"uri":"http://web.archive.org/web/20111111021045/http://www.bind.upatras.gr/"
},
{"datetime":"2011-12-13T13:41:07Z",
"uri":"http://web.archive.org/web/20111213134107/http://www.bind.upatras.gr/"
},
{"datetime":"2012-02-23T02:37:42Z",
"uri":"http://web.archive.org/web/20120223023742/http://bind.upatras.gr/"
},
{"datetime":"2012-04-14T22:18:00Z",
"uri":"http://web.archive.org/web/20120414221800/http://bind.upatras.gr/"
}
]
 },"timemap_uri": {
"json_format": "http://labs.mementoweb.org/timemap/json/1/http://bind.upatras.gr/"}
 }