{"original_uri":"http://enaromatic.bio.demokritos.gr/",
"timegate_uri":"http://timetravel.mementoweb.org/timegate/http://enaromatic.bio.demokritos.gr/",
"mementos": {
"list": [
{"datetime":"2016-02-14T01:08:23Z",
"uri":"http://web.archive.org/web/20160214010823/http://enaromatic.bio.demokritos.gr/"
}
]
 },"timemap_uri": {
"json_format": "http://labs.mementoweb.org/timemap/json/1/http://enaromatic.bio.demokritos.gr/"}
 }