{"original_uri":"http://lpre.cperi.certh.gr/watermim/",
"timegate_uri":"http://timetravel.mementoweb.org/timegate/http://lpre.cperi.certh.gr/watermim/",
"mementos": {
"list": [
{"datetime":"2010-12-26T17:46:28Z",
"uri":"http://web.archive.org/web/20101226174628/http://lpre.cperi.certh.gr/watermim"
},
{"datetime":"2010-12-26T17:46:28Z",
"uri":"http://web.archive.org/web/20101226174628/http://lpre.cperi.certh.gr/watermim/"
},
{"datetime":"2011-04-24T15:55:41Z",
"uri":"http://web.archive.org/web/20110424155541/http://lpre.cperi.certh.gr/watermim/"
},
{"datetime":"2014-07-07T10:00:34Z",
"uri":"http://web.archive.org/web/20140707100034/http://lpre.cperi.certh.gr/watermim"
},
{"datetime":"2014-07-07T10:00:34Z",
"uri":"http://web.archive.org/web/20140707100034/http://lpre.cperi.certh.gr/watermim/"
},
{"datetime":"2015-04-29T06:28:39Z",
"uri":"http://web.archive.org/web/20150429062839/http://lpre.cperi.certh.gr/watermim/"
}
]
 },"timemap_uri": {
"json_format": "http://labs.mementoweb.org/timemap/json/1/http://lpre.cperi.certh.gr/watermim/"}
 }