{"original_uri":"http://aceos.telecom.ntua.gr",
"timegate_uri":"http://timetravel.mementoweb.org/timegate/http://aceos.telecom.ntua.gr",
"mementos": {
"list": [
{"datetime":"2005-07-28T11:38:40Z",
"uri":"http://web.archive.org/web/20050728113840/http://aceos.telecom.ntua.gr/"
},
{"datetime":"2005-11-04T00:17:33Z",
"uri":"http://web.archive.org/web/20051104001733/http://aceos.telecom.ntua.gr/"
},
{"datetime":"2008-12-10T15:49:28Z",
"uri":"http://web.archive.org/web/20081210154928/http://aceos.telecom.ntua.gr/"
},
{"datetime":"2009-02-12T18:10:50Z",
"uri":"http://web.archive.org/web/20090212181050/http://aceos.telecom.ntua.gr/"
}
]
 },"timemap_uri": {
"json_format": "http://labs.mementoweb.org/timemap/json/1/http://aceos.telecom.ntua.gr"}
 }