{"original_uri":"http://esperia.iesl.forth.gr/~ppm/DALHM/",
"timegate_uri":"http://timetravel.mementoweb.org/timegate/http://esperia.iesl.forth.gr/~ppm/DALHM/",
"mementos": {
"list": [
{"datetime":"2007-01-23T02:02:39Z",
"uri":"http://web.archive.org/web/20070123020239/http://esperia.iesl.forth.gr/~ppm/DALHM/"
},
{"datetime":"2013-12-03T09:24:48Z",
"uri":"http://web.archive.org/web/20131203092448/http://esperia.iesl.forth.gr/~ppm/DALHM"
},
{"datetime":"2013-12-03T09:24:48Z",
"uri":"http://web.archive.org/web/20131203092448/http://esperia.iesl.forth.gr/~ppm/DALHM/"
},
{"datetime":"2013-12-05T00:31:49Z",
"uri":"http://web.archive.org/web/20131205003149/http://esperia.iesl.forth.gr/~ppm/DALHM/"
}
]
 },"timemap_uri": {
"json_format": "http://labs.mementoweb.org/timemap/json/1/http://esperia.iesl.forth.gr/~ppm/DALHM/"}
 }