{"original_uri":"http://starfish.ccslab.aueb.gr",
"timegate_uri":"http://timetravel.mementoweb.org/timegate/http://starfish.ccslab.aueb.gr",
"mementos": {
"list": [
{"datetime":"2001-04-19T22:38:17Z",
"uri":"http://web.archive.org/web/20010419223817/http://starfish.ccslab.aueb.gr/"
},
{"datetime":"2001-05-19T12:17:19Z",
"uri":"http://web.archive.org/web/20010519121719/http://starfish.ccslab.aueb.gr/"
},
{"datetime":"2001-07-23T16:09:02Z",
"uri":"http://web.archive.org/web/20010723160902/http://starfish.ccslab.aueb.gr/"
},
{"datetime":"2001-10-02T13:16:59Z",
"uri":"http://web.archive.org/web/20011002131659/http://starfish.ccslab.aueb.gr/"
},
{"datetime":"2001-10-02T13:17:06Z",
"uri":"http://web.archive.org/web/20011002131706/http://starfish.ccslab.aueb.gr/"
},
{"datetime":"2002-01-25T13:39:00Z",
"uri":"http://web.archive.org/web/20020125133900/http://starfish.ccslab.aueb.gr/"
},
{"datetime":"2002-08-08T10:28:53Z",
"uri":"http://web.archive.org/web/20020808102853/http://starfish.ccslab.aueb.gr/"
},
{"datetime":"2009-08-25T21:35:51Z",
"uri":"http://web.archive.org/web/20090825213551/http://starfish.ccslab.aueb.gr/"
}
]
 },"timemap_uri": {
"json_format": "http://labs.mementoweb.org/timemap/json/1/http://starfish.ccslab.aueb.gr"}
 }