{"original_uri":"http://theory.physics.uoi.gr/corfu2001/main.html",
"timegate_uri":"http://timetravel.mementoweb.org/timegate/http://theory.physics.uoi.gr/corfu2001/main.html",
"mementos": {
"list": [
{"datetime":"2003-05-13T02:53:10Z",
"uri":"http://web.archive.org/web/20030513025310/http://theory.physics.uoi.gr/corfu2001/main.html"
},
{"datetime":"2003-05-13T02:53:10Z",
"uri":"http://web.archive.bibalex.org:80/web/20030513025310/http://theory.physics.uoi.gr/corfu2001/main.html"
},
{"datetime":"2003-07-21T02:26:38Z",
"uri":"http://web.archive.bibalex.org:80/web/20030721022638/http://theory.physics.uoi.gr/corfu2001/main.html"
},
{"datetime":"2003-09-09T10:52:03Z",
"uri":"http://web.archive.org/web/20030909105203/http://theory.physics.uoi.gr/corfu2001/main.html"
},
{"datetime":"2003-09-09T10:52:03Z",
"uri":"http://web.archive.bibalex.org:80/web/20030909105203/http://theory.physics.uoi.gr/corfu2001/main.html"
},
{"datetime":"2003-11-20T11:54:29Z",
"uri":"http://web.archive.bibalex.org:80/web/20031120115429/http://theory.physics.uoi.gr/corfu2001/main.html"
},
{"datetime":"2004-09-26T17:43:04Z",
"uri":"http://web.archive.org/web/20040926174304/http://theory.physics.uoi.gr/corfu2001/main.html"
},
{"datetime":"2004-09-26T17:43:04Z",
"uri":"http://web.archive.bibalex.org:80/web/20040926174304/http://theory.physics.uoi.gr/corfu2001/main.html"
},
{"datetime":"2004-11-02T23:09:37Z",
"uri":"http://web.archive.org/web/20041102230937/http://theory.physics.uoi.gr/corfu2001/main.html"
},
{"datetime":"2004-11-02T23:09:37Z",
"uri":"http://web.archive.bibalex.org:80/web/20041102230937/http://theory.physics.uoi.gr/corfu2001/main.html"
},
{"datetime":"2007-03-21T19:59:30Z",
"uri":"http://web.archive.org/web/20070321195930/http://theory.physics.uoi.gr/corfu2001/main.html"
},
{"datetime":"2009-09-11T04:20:00Z",
"uri":"http://web.archive.org/web/20090911042000/http://theory.physics.uoi.gr/corfu2001/main.html"
}
]
 },"timemap_uri": {
"json_format": "http://labs.mementoweb.org/timemap/json/1/http://theory.physics.uoi.gr/corfu2001/main.html"}
 }