{"original_uri":"http://www.gdt.gr/Dipsylan.html",
"timegate_uri":"http://timetravel.mementoweb.org/timegate/http://www.gdt.gr/Dipsylan.html",
"mementos": {
"list": [
{"datetime":"2005-01-04T01:03:02Z",
"uri":"http://web.archive.org/web/20050104010302/http://www.gdt.gr/Dipsylan.html"
},
{"datetime":"2008-03-24T01:58:56Z",
"uri":"http://web.archive.org/web/20080324015856/http://www.gdt.gr/Dipsylan.html"
}
]
 },"timemap_uri": {
"json_format": "http://labs.mementoweb.org/timemap/json/1/http://www.gdt.gr/Dipsylan.html"}
 }