{"original_uri":"http://www.aegean.gr/geogrpaphy/autohazard/",
"timegate_uri":"http://timetravel.mementoweb.org/timegate/http://www.aegean.gr/geogrpaphy/autohazard/",
"mementos": {
"list": [
{"datetime":"2003-05-07T08:08:27Z",
"uri":"http://web.archive.org/web/20030507080827/http://www.aegean.gr/geogrpaphy/autohazard/"
},
{"datetime":"2003-10-28T17:36:19Z",
"uri":"http://web.archive.org/web/20031028173619/http://www.aegean.gr/geogrpaphy/autohazard/"
},
{"datetime":"2004-02-03T04:03:33Z",
"uri":"http://web.archive.org/web/20040203040333/http://www.aegean.gr/geogrpaphy/autohazard/"
},
{"datetime":"2008-04-11T06:48:41Z",
"uri":"http://web.archive.org/web/20080411064841/http://www.aegean.gr/geogrpaphy/autohazard/"
}
]
 },"timemap_uri": {
"json_format": "http://labs.mementoweb.org/timemap/json/1/http://www.aegean.gr/geogrpaphy/autohazard/"}
 }