{"original_uri":"http://www.bpr-logistics.trans.aueb.gr",
"timegate_uri":"http://timetravel.mementoweb.org/timegate/http://www.bpr-logistics.trans.aueb.gr",
"mementos": {
"list": [
{"datetime":"2002-11-23T02:44:55Z",
"uri":"http://web.archive.org/web/20021123024455/http://www.bpr-logistics.trans.aueb.gr/"
},
{"datetime":"2003-04-04T08:19:21Z",
"uri":"http://web.archive.org/web/20030404081921/http://www.bpr-logistics.trans.aueb.gr/"
},
{"datetime":"2003-06-24T15:52:45Z",
"uri":"http://web.archive.org/web/20030624155245/http://www.bpr-logistics.trans.aueb.gr/"
},
{"datetime":"2003-12-07T04:05:43Z",
"uri":"http://web.archive.org/web/20031207040543/http://www.bpr-logistics.trans.aueb.gr/"
},
{"datetime":"2004-02-25T02:52:43Z",
"uri":"http://web.archive.org/web/20040225025243/http://www.bpr-logistics.trans.aueb.gr/"
},
{"datetime":"2014-10-15T17:45:48Z",
"uri":"http://web.archive.org/web/20141015174548/http://www.bpr-logistics.trans.aueb.gr/"
}
]
 },"timemap_uri": {
"json_format": "http://labs.mementoweb.org/timemap/json/1/http://www.bpr-logistics.trans.aueb.gr"}
 }