{"original_uri":"http://www.bic.sk/etinne/index_eng.htm",
"timegate_uri":"http://timetravel.mementoweb.org/timegate/http://www.bic.sk/etinne/index_eng.htm",
"mementos": {
"list": [
{"datetime":"2003-10-22T07:29:32Z",
"uri":"http://web.archive.org/web/20031022072932/http://www.bic.sk/etinne/index_eng.htm"
},
{"datetime":"2004-01-13T08:27:39Z",
"uri":"http://web.archive.org/web/20040113082739/http://www.bic.sk/etinne/index_eng.htm"
}
]
 },"timemap_uri": {
"json_format": "http://labs.mementoweb.org/timemap/json/1/http://www.bic.sk/etinne/index_eng.htm"}
 }