{"original_uri":"http://clandestino.eliamep.gr/",
"timegate_uri":"http://timetravel.mementoweb.org/timegate/http://clandestino.eliamep.gr/",
"mementos": {
"list": [
{"datetime":"2010-04-10T14:25:11Z",
"uri":"http://wayback.archive-it.org/all/20100410142511/http://clandestino.eliamep.gr/"
},
{"datetime":"2010-04-17T13:24:56Z",
"uri":"http://wayback.archive-it.org/all/20100417132456/http://clandestino.eliamep.gr/"
},
{"datetime":"2010-04-24T12:45:54Z",
"uri":"http://wayback.archive-it.org/all/20100424124554/http://clandestino.eliamep.gr/"
},
{"datetime":"2010-05-09T02:08:28Z",
"uri":"http://wayback.archive-it.org/all/20100509020828/http://clandestino.eliamep.gr/"
},
{"datetime":"2012-01-11T09:29:09Z",
"uri":"http://wayback.archive-it.org/all/20120111092909/http://clandestino.eliamep.gr/"
}
]
 },"timemap_uri": {
"json_format": "http://labs.mementoweb.org/timemap/json/1/http://clandestino.eliamep.gr/"}
 }