{"original_uri":"http://commrob.zenon.gr/",
"timegate_uri":"http://timetravel.mementoweb.org/timegate/http://commrob.zenon.gr/",
"mementos": {
"list": [
{"datetime":"2007-12-27T02:03:38Z",
"uri":"http://web.archive.org/web/20071227020338/http://commrob.zenon.gr/"
},
{"datetime":"2008-02-25T06:01:09Z",
"uri":"http://web.archive.org/web/20080225060109/http://commrob.zenon.gr/"
},
{"datetime":"2008-05-13T17:33:05Z",
"uri":"http://web.archive.org/web/20080513173305/http://commrob.zenon.gr/"
},
{"datetime":"2009-07-31T11:24:00Z",
"uri":"http://web.archive.org/web/20090731112400/http://commrob.zenon.gr/"
},
{"datetime":"2009-08-30T23:14:08Z",
"uri":"http://web.archive.org/web/20090830231408/http://commrob.zenon.gr/"
},
{"datetime":"2010-07-25T23:35:52Z",
"uri":"http://web.archive.org/web/20100725233552/http://commrob.zenon.gr/"
}
]
 },"timemap_uri": {
"json_format": "http://labs.mementoweb.org/timemap/json/1/http://commrob.zenon.gr/"}
 }