{"original_uri":"http://www.physics.ntua.gr/comephs/",
"timegate_uri":"http://timetravel.mementoweb.org/timegate/http://www.physics.ntua.gr/comephs/",
"mementos": {
"list": [
{"datetime":"2006-12-18T22:56:40Z",
"uri":"http://web.archive.org/web/20061218225640/http://www.physics.ntua.gr/comephs/"
},
{"datetime":"2007-07-01T00:56:50Z",
"uri":"http://web.archive.org/web/20070701005650/http://www.physics.ntua.gr/comephs/"
},
{"datetime":"2007-07-02T19:54:01Z",
"uri":"http://web.archive.org/web/20070702195401/http://www.physics.ntua.gr/comephs/"
},
{"datetime":"2011-02-08T11:18:39Z",
"uri":"http://web.archive.org/web/20110208111839/http://www.physics.ntua.gr/comephs/"
},
{"datetime":"2015-06-16T15:07:05Z",
"uri":"http://web.archive.org/web/20150616150705/http://www.physics.ntua.gr/comephs/"
}
]
 },"timemap_uri": {
"json_format": "http://labs.mementoweb.org/timemap/json/1/http://www.physics.ntua.gr/comephs/"}
 }