{"original_uri":"http://www.nut.uoa.gr/hector/about.asp",
"timegate_uri":"http://timetravel.mementoweb.org/timegate/http://www.nut.uoa.gr/hector/about.asp",
"mementos": {
"list": [
{"datetime":"2007-10-20T00:29:40Z",
"uri":"http://web.archive.org/web/20071020002940/http://www.nut.uoa.gr/hector/about.asp"
},
{"datetime":"2007-10-20T00:29:40Z",
"uri":"http://web.archive.bibalex.org:80/web/20071020002940/http://www.nut.uoa.gr/hector/about.asp"
},
{"datetime":"2007-11-19T09:16:24Z",
"uri":"http://web.archive.org/web/20071119091624/http://www.nut.uoa.gr/hector/about.asp"
},
{"datetime":"2007-11-19T09:16:24Z",
"uri":"http://web.archive.bibalex.org:80/web/20071119091624/http://www.nut.uoa.gr/hector/about.asp"
},
{"datetime":"2007-12-22T11:59:49Z",
"uri":"http://web.archive.org/web/20071222115949/http://www.nut.uoa.gr/hector/about.asp"
},
{"datetime":"2007-12-22T11:59:49Z",
"uri":"http://web.archive.bibalex.org:80/web/20071222115949/http://www.nut.uoa.gr/hector/about.asp"
},
{"datetime":"2008-02-29T12:39:03Z",
"uri":"http://web.archive.org/web/20080229123903/http://www.nut.uoa.gr/hector/about.asp"
},
{"datetime":"2009-11-13T05:12:26Z",
"uri":"http://web.archive.org/web/20091113051226/http://www.nut.uoa.gr/hector/about.asp"
},
{"datetime":"2011-02-18T20:28:16Z",
"uri":"http://web.archive.org/web/20110218202816/http://www.nut.uoa.gr/hector/about.asp"
},
{"datetime":"2013-03-23T15:08:39Z",
"uri":"http://web.archive.org/web/20130323150839/http://www.nut.uoa.gr/hector/about.asp"
},
{"datetime":"2013-05-28T03:42:37Z",
"uri":"http://web.archive.org/web/20130528034237/http://www.nut.uoa.gr/hector/about.asp"
},
{"datetime":"2015-08-03T01:42:32Z",
"uri":"http://web.archive.org/web/20150803014232/http://www.nut.uoa.gr/hector/about.asp"
}
]
 },"timemap_uri": {
"json_format": "http://labs.mementoweb.org/timemap/json/1/http://www.nut.uoa.gr/hector/about.asp"}
 }