<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Home | Biaxial Nematic Devices</title>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link rel="shortcut icon" href="/misc/favicon.ico" type="image/x-icon" />
  <link type="text/css" rel="stylesheet" media="all" href="/modules/node/node.css?3" />
<link type="text/css" rel="stylesheet" media="all" href="/modules/system/defaults.css?3" />
<link type="text/css" rel="stylesheet" media="all" href="/modules/system/system.css?3" />
<link type="text/css" rel="stylesheet" media="all" href="/modules/system/system-menus.css?3" />
<link type="text/css" rel="stylesheet" media="all" href="/modules/user/user.css?3" />
<link type="text/css" rel="stylesheet" media="all" href="/sites/all/modules/announcements/announcements.css?3" />
<link type="text/css" rel="stylesheet" media="all" href="/sites/all/modules/dhtml_menu/dhtml_menu.css?3" />
<link type="text/css" rel="stylesheet" media="all" href="/sites/all/modules/fckeditor/fckeditor.css?3" />
<link type="text/css" rel="stylesheet" media="all" href="/themes/fblike/style.css?3" />
  <script type="text/javascript" src="/misc/jquery.js?3"></script>
<script type="text/javascript" src="/misc/drupal.js?3"></script>
<script type="text/javascript" src="/sites/all/modules/dhtml_menu/dhtml_menu.js?3"></script>
<script type="text/javascript">
<!--//--><![CDATA[//><!--
jQuery.extend(Drupal.settings, { "basePath": "/", "dhtmlMenu": { "slide": "slide", "siblings": "siblings", "clone": "clone", "relativity": 0, "children": 0, "doubleclick": 0 } });
//--><!]]>
</script>
</head>

<body>
  <div id="header_bar">
            <div id="header_logo">
      <a href="/">
        <img src="/sites/default/files/bind_logo_header.jpg" alt=" logo" id="logo" />        <br/><h1></h1>              </a>
    </div>
        <div id="navigator" class="clearfix">
      <div class="center_box">
                <ul>
                <li class="active first"><a href="/?q=node/1" class="active">Home</a></li>
                <li><a href="/?q=node/2">Research Staff</a></li>
                <li><a href="/?q=node/3">Activities</a></li>
                <li><a href="/?q=node/4">Job Openings</a></li>
                <li><a href="/?q=node/5">Publications</a></li>
                <li><a href="/?q=node">News</a></li>
                <li><a href="/?q=node/6">Contact</a></li>
                <li><a href="/?q=node/21">Log in/out</a></li>
                </ul>
              </div>
    </div>
  </div>
  <div class="middle-container clearfix">
    <div class="content_header">
      <div class="header_image">
        <h1>Home</h1>      </div>
          </div>
            <div class="content_pad"></div>
    <div class="content_bg clearfix">
        <div class="side_nav">
      <div class="block">
    <div class="block-header">
    <h3>Project Members</h3>
  </div>
    <div class="block-content">
    <ul class="menu"><li class="leaf first dhtml-menu "><a href="/?q=node/8" title="Patras (UPAT)" id="dhtml_menu-125">Patras (UPAT)</a></li>
<li class="leaf  dhtml-menu "><a href="/?q=node/9" title="Bologna (UNIBO)" id="dhtml_menu-126">Bologna (UNIBO)</a></li>
<li class="leaf  dhtml-menu "><a href="/?q=node/10" title="Dublin  (TCD)" id="dhtml_menu-127">Dublin  (TCD)</a></li>
<li class="leaf  dhtml-menu "><a href="/?q=node/11" title="Freiburg (ALU-FR)" id="dhtml_menu-128">Freiburg (ALU-FR)</a></li>
<li class="leaf  dhtml-menu "><a href="/?q=node/12" title="Halle (MLU)" id="dhtml_menu-129">Halle (MLU)</a></li>
<li class="leaf  dhtml-menu "><a href="/?q=node/13" title="Hull (UHULL)" id="dhtml_menu-130">Hull (UHULL)</a></li>
<li class="leaf last dhtml-menu "><a href="/?q=node/14" title="Oxford (UOXF)" id="dhtml_menu-131">Oxford (UOXF)</a></li>
</ul>  </div>
</div>
    </div>
        <div class="content_global">
                        <div class="content_main">
                        <div class="node">
      <span class="submitted"></span>
  <div class="content"><p style="color: rgb(51, 102, 153);"><strong>Biaxial Nematic Devices</strong></p>
<p><strong>BIND</strong>, an FP7 funded 3-year research project on biaxial nematic electro-optic device systems and materials, aims to provide the basic know-how enabling the production of a new generation of fast LC displays. It comprises:</p>
<ol type="i">
<li>deepening the fundamental understanding of structure-properties relationships in biaxial nematic materials, with a particular view to bring their range of stability down to room temperature,</li>
<li>developing experimental protocols for the identification and quantification of biaxiality and</li>
<li>investigating novel alignment methods and candidate display architectures.</li>
</ol>
<p>The <strong>technological objective </strong>is to demonstrate the first working device based on nematic biaxiality.</p>
<p>To go from basic understanding of materials properties to working devices, an interdisciplinary consortium of leading research teams has been assembled. Expertise in BIND encompasses state-of-the-art chemical synthesis and characterisation, physical measurement, molecular modelling, computer simulation and design of liquid crystal devices. A variety of liquid crystal types will be assessed, ranging from low-molar-mass nematics to oligomers, multipodes, linear polymers and elastomers. This project by the EC - FP7 ICT Programme will generate important knowledge for new industrial application opportunities. In addition to the active engagement of all the partners towards that goal, the contribution of the members of the Industrial Advisory Board in certain key aspects of this highly prospective project is crucial to its success.</p>
<p><strong>Consortium</strong>:</p>
<ol>
<li><em>University of Patras </em>(UPAT), Greece, (Prof. D. J. Photinos, Coordinator)</li>
<li><em>Universita di Bologna </em>(UNIBO), Italy, (Prof. C. Zannoni)</li>
<li><em><img width="74" height="54" alt="" src="/sites/default/files/7th_1.jpg" style="float: right;" />Trinity College </em>(TCD), Ireland, (Prof J. Vij)</li>
<li><em>Universitaet Freiburg </em>(ALU-FR), Germany, (Prof. H. Finkelmann)</li>
<li><em>Universitaet Halle Wittenberg </em>(MLU), Germany, (Prof. C. Tschierske)</li>
<li><em>Univerity of Hull </em>(UHULL), UK, (Dr. G. H. Mehl)</li>
<li><em><img width="74" height="50" alt="" src="/sites/default/files/eu.jpg" style="float: right;" />University of Oxford </em>(UOXF), UK, (Prof. S. Elston)</li>
</ol>
<p><strong>Advisory Board</strong>: <em>Merck KGaA </em>(Germany) and <em>QinetiQ ltd </em>(UK).</p>
</div>
    </div>
              </div>
    </div>
  </div>
</div>
<div id="footer">
  <div id="footer_content">
    <!--
	<div class="left"><a href="http://www.bonvga.net/fblike">fblike</a> by <a href="http://www.bonvga.net/">bonvga</a></div>
	-->
	<div class="left"><a href="/?q=user/login">Login</a></div>
        <div class="right"><p>&nbsp;Copyright 2009, University of Patras</p></div>
      </div>
  </div>
</body>
</html>
