<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<!-- Use IE7 mode -->

<meta http-equiv="X-UA-Compatible" content="IE=7" />
<title>ENAROMaTIC Description</title>
<style type="text/css">
<!--
body {
	margin-left: 260px;
	margin-top: 150px;
	margin-right: 0px;
	margin-bottom: 0px;
	background-color: #FFFFFF;
}
.style2 {
	font-family: Calibri;
	font-size: 30px;
	font-weight: bold;
	color: #004182;
}
#Layer1 {
	position:absolute;
	left:289px;
	top:257px;
	width:325px;
	height:36px;
	z-index:1;
	background-color: #FFFFCC;
	padding-left: 5px;
	padding-top: 5px;
	padding-bottom: 5px;
	padding-right: 5px;
	visibility: hidden;
}
.style17 {font-size: 16px; font-family: Calibri; }
.style18 {font-size: 16px}
.style19 {font-family: Calibri}
.style21 {font-family: Calibri; font-size: 10px; }
.style23 {
	font-family: Calibri;
	color: #004182;
	font-weight: bold;
}
.style24 {
	font-size: 12px;
	font-weight: bold;
	color: #004182;
}
.style26 {
	color: #000066;
	font-weight: bold;
}
  #uberbar  { 
  border-bottom:1px solid #ffffff; 
  background:#ffffff; 
  padding:0px 0px; 
  position:fixed; 
  top:0; 
  left:0; 
  z-index:1000; 
  width:100%;
}
-->
</style>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" /><div id="uberbar"> 
<img src="images/ENA_blue_F1.jpg" />
</div>
</head>

<script type="text/JavaScript">
<!--
function MM_findObj(n, d) { //v4.01
  var p,i,x;  if(!d) d=document; if((p=n.indexOf("?"))>0&&parent.frames.length) {
    d=parent.frames[n.substring(p+1)].document; n=n.substring(0,p);}
  if(!(x=d[n])&&d.all) x=d.all[n]; for (i=0;!x&&i<d.forms.length;i++) x=d.forms[i][n];
  for(i=0;!x&&d.layers&&i<d.layers.length;i++) x=MM_findObj(n,d.layers[i].document);
  if(!x && d.getElementById) x=d.getElementById(n); return x;
}

function MM_showHideLayers() { //v6.0
  var i,p,v,obj,args=MM_showHideLayers.arguments;
  for (i=0; i<(args.length-2); i+=3) if ((obj=MM_findObj(args[i]))!=null) { v=args[i+2];
    if (obj.style) { obj=obj.style; v=(v=='show')?'visible':(v=='hide')?'hidden':v; }
    obj.visibility=v; }
}

//-->
</script>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" /></head>

<body>
<!-- DO NOT MOVE! The following AllWebMenus linking code section must always be placed right AFTER the BODY tag-->
<!-- ******** BEGIN ALLWEBMENUS CODE FOR menu ******** -->
<script type="text/javascript">var MenuLinkedBy="AllWebMenus [4]",awmMenuName="menu",awmBN="860";awmAltUrl="";</script><script charset="UTF-8" src="menu.js" type="text/javascript"></script><script type="text/javascript">awmBuildMenu();</script>
<!-- ******** END ALLWEBMENUS CODE FOR menu ******** -->

<table width="552" border="0" cellpadding="0" cellspacing="0">
  <!--DWLayoutTable-->
  
  <tr>
    <td width="10" height="227"></td>
    <td colspan="5" valign="top"><p class="style2">ENAROMaTIC </p>      
    <p class="style17" onmouseover="MM_showHideLayers('Layer1','','show')" onmouseout="MM_showHideLayers('Layer1','','hide')"><span class="style18"><strong>Title: </strong>European Network  for Advanced Research on Olfaction for Malaria Transmitting Insect Control <br />
          <strong>Contract/Grant agreement  number: </strong>222927<br />
          <strong>Duration:</strong> 48 months<br />
          <strong>Starting date:</strong> 01/12/2008<br />
          <strong>Instrument: </strong>HEALTH-2007-2.3.2-9 Blocking the transmission of  malaria: the mosquito vector target <br />
          <strong>Coordinator</strong>: <a href="http://www.demokritos.gr/default.aspx?lang=en" target="_parent">NCSR &quot;Demokritos&quot;</a>, <a href="http://bio.demokritos.gr/index.php?option=com_content&amp;view=article&amp;id=34%3A2009-09-21-22-00-34&amp;catid=36%3A2009-09-21-17-36-27&amp;Itemid=73&amp;lang=en" target="_parent" onmouseover="MM_showHideLayers('Layer1','','show')" onmouseout="MM_showHideLayers('Layer1','','hide')">Prof. Kostas Iatrou </a><br />
      <strong>Administrative director: </strong>Dimitris Raptopoulos PhD. </span></p>    </td>
  <td width="15" class="style18">&nbsp;</td>
  </tr>
  <tr>
    <td height="22" class="style18"></td>
    <td width="180" class="style18"></td>
    <td width="10" class="style18"></td>
    <td width="206" class="style18"></td>
    <td width="16" class="style18">&nbsp;</td>
    <td width="115" rowspan="3" valign="top" class="style18"><img src="images/mozy-earth.jpg" width="113" height="168" /></td>
  <td class="style18"></td>
  </tr>
  
  
  
  
  
  
  
  <tr>
    <td height="114" class="style18"></td>
    <td colspan="3" valign="top" class="style18"><div align="justify"><span class="style19"><strong>Problem:</strong><br />
    The inability of health authorities to control the spread of malaria in  places where the disease is endemic due to ineffectiveness of existing drug  treatments, lack of effective vaccines and resistance of the mosquito vector to  insecticides. </span></div></td>
    <td class="style18">&nbsp;</td>
    <td class="style18"></td>
  </tr>
  <tr>
    <td height="32" class="style18"></td>
    <td class="style18"></td>
    <td class="style18"></td>
    <td class="style18"></td>
    <td class="style18"></td>
    <td class="style18"></td>
  </tr>
  <tr>
    <td height="133" class="style18"></td>
    <td rowspan="2" valign="top" class="style18"><img src="images/Mosquitos cross hair1.gif" width="179" height="135" /></td>
  <td class="style18">&nbsp;</td>
    <td colspan="4" valign="top" class="style18"><div align="justify"><span class="style19"><strong>Aim:</strong><br />
    To interfere with the capacity of the female mosquito (disease vector)  to detect the presence of odors of human origin in its environment and, thus,  prevent it from obtaining a blood meal from the host and transmitting the  malaria parasite in the process.&nbsp; </span></div></td>
  </tr>
  
  <tr>
    <td height="2" class="style18"></td>
    <td class="style18"></td>
    <td class="style18"></td>
    <td class="style18"></td>
    <td class="style18"></td>
    <td class="style18"></td>
  </tr>
  <tr>
    <td height="19" class="style18"></td>
    <td class="style18">&nbsp;</td>
    <td class="style18"></td>
    <td class="style18"></td>
    <td class="style18"></td>
    <td class="style18"></td>
    <td class="style18"></td>
  </tr>
  <tr>
    <td height="28" class="style18"></td>
    <td class="style18"><div align="center"><span class="style23">PRESS RELEASE<br />
      4/4/2012</span><br />
        <br />
    </div></td>
    <td colspan="4" bgcolor="#FFFF99" class="style18"><div align="justify" class="style19"><span class="style26">ENAROMaTIC develops a novel, highly effective, environmentally responsible repellent against the malaria mosquito vector, <em>Anopheles gambiae </em></span><span class="style24"> <a href="PressRelease.html" target="_self">more&gt;&gt; </a></span></div></td>
    <td class="style18"></td>
  </tr>
  <tr>
    <td height="28" class="style18"></td>
    <td class="style18">&nbsp;</td>
    <td class="style18"></td>
    <td class="style18"></td>
    <td class="style18"></td>
    <td class="style18"></td>
    <td class="style18"></td>
  </tr>
  <tr>
    <td height="28" class="style18"></td>
    <td class="style18">&nbsp;</td>
    <td class="style18"></td>
    <td class="style18"></td>
    <td colspan="3" class="style18"><div align="right"><span class="style21">last update 06.04.2012</span></div></td>
  </tr>
</table>
</body>
</html>
