<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
<!-- Mirrored from www.younex.unige.ch/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Mon, 16 Nov 2015 11:23:26 GMT -->
<head profile="http://www.acme.com/profiles/core http://dublincore.org/documents/dcq-html/"><meta content="noimageindex" name="robots" /><link href="../purl.org/dc/elements/1.1/index.html" rel="schema.DC" /><link href="../purl.org/dc/terms/index.html" rel="schema.DCTERMS" /><title>Welcome - Younex - UNIGE</title><meta content="text/html; charset=iso-8859-1" http-equiv="Content-Type" /><meta content="" name="keywords" /><meta content=" " name="description" /><meta content="2013-06-10 16:18:39" name="revised" /><meta content="Welcome" name="DC:title" /><meta content="" name="DC:subject" /><meta content=" " name="DC:description" /><meta content="University of Geneva" name="DC:publisher" /><meta content="2013-06-10 16:18:39" name="DC:date" /><meta content="en" name="DC:language" /><meta content="University of Geneva" name="DC:rights" /><link type="text/css" rel="stylesheet" href="unizh/authoring/css/old_main.css" /><link href="css/old_institute.css" rel="stylesheet" type="text/css" /><script src="unizh/authoring/javascript/uni.js" type="text/javascript"><!----> </script><script src="jquery/jquery-latest.min.js" type="text/javascript"><!----> </script><script src="jquery/autoHeight.js" type="text/javascript"><!----> </script><script src="jquery/jquery.tablesorter.min.js" type="text/javascript"><!----> </script><script src="jquery/jquery.metadata.js" type="text/javascript"><!----> </script><script src="jquery/slides.min.jquery.js" type="text/javascript"><!----> </script></head><body><div class="bodywidth"><a accesskey="1" href="#navigation" title="Aller à la navigation"><!----></a><a accesskey="2" href="#content" title="Aller au contenu"><!----></a><a name="top"><!----></a><div class="index" id="headerarea"><div id="headerimgpos"><div class="imgunilogo"><a href="http://www.unige.ch/"><img alt="UNIGE logo" height="79" src="unizh/authoring/images/blank.gif" width="180" /></a></div><div class="imginstitute">
           
        </div></div><div id="headertitelpos"><div id="servicenavpos"><form accept-charset="utf-8" action="http://search.unige.ch/" id="formsearch" method="get"><div class="serviceform"><input accesskey="5" name="text" title="chercher" type="text" /></div><div class="serviceform"><label for="formsearch"><a href="javascript:document.forms['formsearch'].submit();">Search</a></label></div></form> | 
      <a accesskey="0" href="index.html">Home</a>
        |
      <a accesskey="3" href="contact.html">Contacts</a>
        |
      <a href="http://my.unige.ch/">UNIGE Portal</a> |
      <a href="http://wadme.unige.ch:3149/pls/opbot/annuaire" target="_blank">Annuaire</a></div><div><h2>Université de Genève</h2></div><h1><span><a href="index.html">Younex</a></span></h1></div></div><div class="floatclear"><!----></div><div id="primarnav"> </div><div class="floatclear"><!----></div><div class="endheaderline"><img alt="" height="1" src="unizh/authoring/images/1.gif" width="1" /></div><div id="breadcrumbnav"><a href="http://www.unige.ch/en/">University of Geneva</a>
         &gt; <a href="index.html">YOUNEX</a></div><div id="toolnav"><div class="icontextpos"><div id="icontext"> </div></div><a href="#" onClick="window.open('index_en.print.html', '', 'width=700,height=700,menubar=yes,scrollbars')" onmouseout="changeIcontext('')" onmouseover="changeIcontext('Print this page')"><img alt="Print this page" height="11" src="unizh/authoring/images/icon_print.png" width="16" /></a></div><div class="floatclear"><!----></div><div id="col1"><div id="secnav"><a class="namedanchor" name="navigation"><!----></a><ul><li><a href="FC-1.html">Final Conference</a></li><li><a href="description.html">Project description</a></li><li><a href="partners.html">Partners</a></li><li><a href="Work.html">Work description</a></li><li><a href="Products.html">Project Products</a></li><li><a href="Meetings.html">Events</a></li><li><a href="AdvisoryBoard.html">Advisory Board</a></li><li><a href="Links.html">Links</a></li><li><a href="contact.html">Contacts</a></li><li><a href="Media.html">Younex in the media</a></li><li><a href="intranet.html">Intranet</a></li></ul><!----></div></div><div class="contcol2"><div class="relatedbox">
<div class="teaser"><h3>Download YOUNEX Booklet<!----></h3><p>
<a href="StockPDF/younex-brochure_9.10.08.pdf" target="_blank">Younex Brochure (English)<!----></a> </p><p><a href="StockPDF/booklet-french.pdf" target="_blank">French<!----></a> /<a href="StockPDF/booklet-italian.pdf" target="_newwin"> Italian<!----></a> / <a href="StockPDF/booklet-swedish.pdf" target="_blank">Swedish<!----></a> /<a href="StockPDF/brochure-german.pdf" target="_blank">German<!----></a>/  <a href="StockPDF/YOUNEXbrochurePolish.pdf" target="_blank">Polish<!----></a></p></div>

<div class="teaser"><h3>Newsletter<!----></h3><a class="internal" href="newsletter.html"><!----></a><a class="unige" href="StockPDF/younex-newsletter-10-2008.pdf" target="_blank">Younex Newsletter 1</a><a class="unige" href="StockPDF/younex-newsletter-4-2009.pdf" target="_blank">Younex Newsletter 2 </a><a class="unige" href="StockPDF/younex-newsletter-OCTOBRE-2009.pdf" target="_blank">Younex Newsletter 3</a><a class="unige" href="StockPDF/younex-newsletter-4-2010.pdf" target="_blank">Younex Newsletter 4</a><a class="unige" href="StockPDF/younex-newsletter-10-2010.pdf" target="_blank">Younex Newsletter 5</a><a class="internal" href="index/younex-newsletter-10-2011.pdf" target="_blank">Younex Newsletter 6</a></div>
<div class="teaser"><h3><!----></h3></div>
<div class="teaser"><a href="http://cordis.europa.eu/fp7/cooperation/home_en.html"><img alt="Seven" src="index/seven.png" width="160" /></a><h3> <!----></h3></div>
<div class="teaser"><a href="http://ec.europa.eu/research/index.cfm"><img alt="Europe" src="index/europe.png" width="160" /></a><h3> <!----></h3></div>

<!----><!----></div><div class="contentarea"><a accesskey="2" name="content"><!----></a><div class="content"><h1>Welcome<!----></h1><div><p>The Younex project is part of the seventh european framework programme and works on youth unemployment and exclusion in Europe. There are six countries participating in the project : Switzerland, Germany, Italy, France, Sweden and Poland.</p><p>
<strong>YOUNEX </strong>Youth, Unemployment, and Exclusion in Europe: A multidimensional approach to understanding the conditions and prospects for social and political integration of young unemployed</p><p>Seventh Framework Programme : Theme Youth and social exclusion</p><p>Grant agreement : No. 21612</p><p /><p /><h2><a class="unige" href="FC-1.html">YOUNEX FINAL CONFERENCE, BRUSSELS, AUGUST 30th</a><a class="namedanchor" name=""><!----></a></h2></div></div><div class="footermargintop"><!----></div><div class="topnav"><a href="#top">top</a></div><div class="solidline"><img alt="" height="1" src="unizh/authoring/images/1.gif" width="1" /></div><div id="footer">© University of Geneva
      | Jun 10, 2013</div></div></div></div></body>
<!-- Mirrored from www.younex.unige.ch/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Mon, 16 Nov 2015 11:25:26 GMT -->
</html>