<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="sk-sk" lang="sk-sk" >
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="Content-Language" content="sk" />
<meta name="author" content="AGLO solutions (www.aglo.sk)" />
<meta name="generator" content="SysCom Content Management System (www.syscom.sk)" />
<meta name="keywords" content="" />
<meta name="description" content="" />
<link href="/include/default.css" type="text/css" rel="stylesheet" />
<title>Overview</title>
</head>
<div id="container">
<div id="icons">
  <a class="sitemap" href="/index.php?ID=7">Site map</a>
  <a class="print" href="./index.php?ID=8&pg=2">Print version</a>
  <a class="home" href="/">Home page</a>
</div>
<div id="content-top"></div>
<div id="content-middle">
  
  
  <div id="header-center">
    <div id="header">
      <div class="banner"></div>
    </div>
  </div>


  <div id="content-center">

    <div id="left">
      
      <div class="block-head">CHOOSE FROM MENU</div>
      <div class="menu">
        <ul><li><a href="/index.php?ID=8" class="menu">Overview</a></li><li><a href="/index.php?ID=10" class="menu">Partners</a></li><li><a href="/index.php?ID=12" class="menu">Contact</a></li><li><a href="/index.php?ID=5" class="menu">Dissemination</a></li></ul>
      </div>
      <div class="block-bottom"></div>
      
      <div class="block-head">SEARCH</div>
      <div class="block-middle">
        <form action="index.php" method="post" name="searchFull"">
	  <input name="ID" value="16" type="hidden"><input class="input" type="text" name="s" value="" />
	  <input type="submit" value=" " class="button-search" />
	</form>
      </div>
      <div class="block-bottom"></div>
      
      <div class="block-head">LOGIN TO INTRANET</div>
      <div class="block-middle">
        <img src="images/lock.gif" align="left" style="margin: 10px 10px 0px 10px;"><span class="login"><br /><br />Login for SILTRANS<br />participants: <a href="/sysadm/index.php">click here</a></span><br /><br />
      </div>
      <div class="block-bottom"></div>

      <div class="block-head">ACKNOWLEDGEMENTS</div>
      <div class="block-middle">
         <img src="images/eu-flag.jpg" align="left" style="margin: 15px 0px 20px 10px;">
         <img src="images/FP7.jpg" align="right" style="margin: 15px 10px 20px 0px;">
         <br /><br /><br /><br /><br /><br /><br />
      </div>
      <div class="block-bottom"></div>
      
    </div>
    
    <div id="page">






<h1>Overview</h1><br />
<h2 style="text-align: center;">Micro and Nanocrystalline Silicide - Refractory Metals FGM</h2>
<h2 style="text-align: center;">for Materials Innovation in Transport Applications</h2>
<p style="text-align: center;">(FP7 project)</p>
<p><strong>Acronym:</strong> SILTRANS</p>
<p style="text-align: left;"><strong>Type of funding scheme:</strong> Small or medium-scale focused research project<br />
<strong><br />
</strong><strong>Project solution:</strong> 10 / 2009 - 9 / 2013<br />
<br />
<strong>Project number:</strong> NMP3-SL-2009-229127<br />
<br />
<strong>Work programme topics addressed:</strong><br />
FP7 NMP-2008.2.5-1 &ldquo;Functionally graded materials for improved mechanical performance&rdquo;<br />
<br />
<span style="font-weight: bold;">C</span><strong>oordinator:</strong><br />
Dr. Ing. Frantisek Simancik<br />
<a href="http://www.umms.sav.sk">Institute of Materials &amp; Machine Mechanics SAS</a>, Bratislava, Slovakia</p>

</div>
  
    
    <div class="cleaner"></div>
  </div>
  
  <div id="footer">
    <div id="foot">Copyright - Siltrans 2010<br />All rights reserved</div>
    <div id="makedby">Powered by: <a href="http://www.syscom.sk">Syscom</a><br />Design by: <a href="http://www.aglo.sk">Aglo solutions</a></div>
  </div>
</div>

<div id="content-bottom"></div>

<div id="makedby"></div>

</div>

</body>




</html>