{"original_uri":"http://hyswitch.physics.uoc.gr/",
"timegate_uri":"http://timetravel.mementoweb.org/timegate/http://hyswitch.physics.uoc.gr/",
"mementos": {
"list": [
{"datetime":"2013-10-16T19:31:24Z",
"uri":"http://web.archive.org/web/20131016193124/http://hyswitch.physics.uoc.gr"
}
]
 },"timemap_uri": {
"json_format": "http://labs.mementoweb.org/timemap/json/1/http://hyswitch.physics.uoc.gr/"}
 }