{"original_uri":"http://lpre.cperi.certh.gr/bioproduction/",
"timegate_uri":"http://timetravel.mementoweb.org/timegate/http://lpre.cperi.certh.gr/bioproduction/",
"mementos": {
"list": [
{"datetime":"2007-12-02T08:30:14Z",
"uri":"http://web.archive.bibalex.org:80/web/20071202083014/http://lpre.cperi.certh.gr/bioproduction/"
},
{"datetime":"2007-12-02T08:30:14Z",
"uri":"http://web.archive.org/web/20071202083014/http://lpre.cperi.certh.gr/bioproduction/"
},
{"datetime":"2009-01-23T21:40:31Z",
"uri":"http://web.archive.org/web/20090123214031/http://lpre.cperi.certh.gr/bioproduction"
},
{"datetime":"2009-01-23T21:40:31Z",
"uri":"http://web.archive.org/web/20090123214031/http://lpre.cperi.certh.gr/bioproduction/"
},
{"datetime":"2009-02-25T11:38:52Z",
"uri":"http://web.archive.org/web/20090225113852/http://lpre.cperi.certh.gr/bioproduction"
},
{"datetime":"2009-02-25T11:38:52Z",
"uri":"http://web.archive.org/web/20090225113852/http://lpre.cperi.certh.gr/bioproduction/"
},
{"datetime":"2010-09-06T12:38:34Z",
"uri":"http://web.archive.org/web/20100906123834/http://lpre.cperi.certh.gr/bioproduction/"
},
{"datetime":"2015-06-14T09:00:48Z",
"uri":"http://web.archive.org/web/20150614090048/http://lpre.cperi.certh.gr/bioproduction/"
}
]
 },"timemap_uri": {
"json_format": "http://labs.mementoweb.org/timemap/json/1/http://lpre.cperi.certh.gr/bioproduction/"}
 }