{"original_uri":"http://mufins.cti.gr/",
"timegate_uri":"http://timetravel.mementoweb.org/timegate/http://mufins.cti.gr/",
"mementos": {
"list": [
{"datetime":"2005-08-12T00:35:08Z",
"uri":"http://web.archive.org/web/20050812003508/http://mufins.cti.gr/"
},
{"datetime":"2012-05-08T17:55:17Z",
"uri":"http://web.archive.org/web/20120508175517/http://mufins.cti.gr/"
}
]
 },"timemap_uri": {
"json_format": "http://labs.mementoweb.org/timemap/json/1/http://mufins.cti.gr/"}
 }