{"original_uri":"http://transportnet.aegean.gr/",
"timegate_uri":"http://timetravel.mementoweb.org/timegate/http://transportnet.aegean.gr/",
"mementos": {
"list": [
{"datetime":"2009-02-17T17:21:39Z",
"uri":"http://web.archive.org/web/20090217172139/http://transportnet.aegean.gr/"
},
{"datetime":"2009-02-18T17:34:14Z",
"uri":"http://web.archive.org/web/20090218173414/http://transportnet.aegean.gr/"
},
{"datetime":"2009-07-31T05:55:44Z",
"uri":"http://web.archive.org/web/20090731055544/http://transportnet.aegean.gr/"
},
{"datetime":"2009-10-20T04:57:58Z",
"uri":"http://web.archive.org/web/20091020045758/http://transportnet.aegean.gr/"
},
{"datetime":"2010-02-18T22:02:06Z",
"uri":"http://web.archive.org/web/20100218220206/http://transportnet.aegean.gr/"
},
{"datetime":"2011-09-30T16:56:50Z",
"uri":"http://web.archive.org/web/20110930165650/http://transportnet.aegean.gr/"
}
]
 },"timemap_uri": {
"json_format": "http://labs.mementoweb.org/timemap/json/1/http://transportnet.aegean.gr/"}
 }