{"original_uri":"http://www.mred.tuc.gr/projects/spatstat/index.html",
"timegate_uri":"http://timetravel.mementoweb.org/timegate/http://www.mred.tuc.gr/projects/spatstat/index.html",
"mementos": {
"list": [
{"datetime":"2007-06-24T05:31:19Z",
"uri":"http://web.archive.org/web/20070624053119/http://www.mred.tuc.gr/projects/spatstat/index.html"
},
{"datetime":"2009-07-12T06:09:02Z",
"uri":"http://web.archive.org/web/20090712060902/http://www.mred.tuc.gr/projects/spatstat/index.html"
},
{"datetime":"2012-12-13T07:45:23Z",
"uri":"http://web.archive.org/web/20121213074523/http://www.mred.tuc.gr/projects/spatstat/index.html"
}
]
 },"timemap_uri": {
"json_format": "http://labs.mementoweb.org/timemap/json/1/http://www.mred.tuc.gr/projects/spatstat/index.html"}
 }