{"original_uri":"http://www.eng.auth.gr/mattas/carera.htm",
"timegate_uri":"http://timetravel.mementoweb.org/timegate/http://www.eng.auth.gr/mattas/carera.htm",
"mementos": {
"list": [
{"datetime":"2007-08-29T18:00:15Z",
"uri":"http://web.archive.org/web/20070829180015/http://www.eng.auth.gr/mattas/carera.htm"
},
{"datetime":"2007-08-29T21:57:05Z",
"uri":"http://web.archive.org/web/20070829215705/http://www.eng.auth.gr/mattas/carera.htm"
},
{"datetime":"2007-11-22T19:22:04Z",
"uri":"http://web.archive.bibalex.org:80/web/20071122192204/http://www.eng.auth.gr/mattas/carera.htm"
},
{"datetime":"2007-11-22T19:22:04Z",
"uri":"http://web.archive.org/web/20071122192204/http://www.eng.auth.gr/mattas/carera.htm"
},
{"datetime":"2007-12-23T15:33:02Z",
"uri":"http://web.archive.bibalex.org:80/web/20071223153302/http://www.eng.auth.gr/mattas/carera.htm"
},
{"datetime":"2007-12-23T15:33:02Z",
"uri":"http://web.archive.org/web/20071223153302/http://www.eng.auth.gr/mattas/carera.htm"
},
{"datetime":"2008-09-15T09:38:11Z",
"uri":"http://web.archive.org/web/20080915093811/http://www.eng.auth.gr/mattas/carera.htm"
},
{"datetime":"2008-10-16T03:19:54Z",
"uri":"http://web.archive.org/web/20081016031954/http://www.eng.auth.gr/mattas/carera.htm"
},
{"datetime":"2009-02-07T07:43:52Z",
"uri":"http://web.archive.org/web/20090207074352/http://eng.auth.gr/mattas/carera.htm"
},
{"datetime":"2010-12-04T08:50:51Z",
"uri":"http://web.archive.org/web/20101204085051/http://www.eng.auth.gr/mattas/carera.htm"
},
{"datetime":"2011-01-02T10:22:57Z",
"uri":"http://web.archive.org/web/20110102102257/http://www.eng.auth.gr/mattas/carera.htm"
},
{"datetime":"2012-10-14T00:37:32Z",
"uri":"http://web.archive.org/web/20121014003732/http://www.eng.auth.gr/mattas/carera.htm"
}
]
 },"timemap_uri": {
"json_format": "http://labs.mementoweb.org/timemap/json/1/http://www.eng.auth.gr/mattas/carera.htm"}
 }