{"original_uri":"http://www.ist-imosan.gr",
"timegate_uri":"http://timetravel.mementoweb.org/timegate/http://www.ist-imosan.gr",
"mementos": {
"list": [
{"datetime":"2007-02-19T14:42:41Z",
"uri":"http://web.archive.org/web/20070219144241/http://www.ist-imosan.gr/"
},
{"datetime":"2007-07-18T01:14:01Z",
"uri":"http://web.archive.org/web/20070718011401/http://www.ist-imosan.gr/"
},
{"datetime":"2007-10-30T17:54:47Z",
"uri":"http://web.archive.org/web/20071030175447/http://www.ist-imosan.gr/"
},
{"datetime":"2007-12-30T05:38:32Z",
"uri":"http://web.archive.org/web/20071230053832/http://www.ist-imosan.gr/"
},
{"datetime":"2008-04-11T15:04:12Z",
"uri":"http://web.archive.org/web/20080411150412/http://www.ist-imosan.gr/"
}
]
 },"timemap_uri": {
"json_format": "http://labs.mementoweb.org/timemap/json/1/http://www.ist-imosan.gr"}
 }