{"original_uri":"http://www.utc.sk/cetra/cetraen/popisprojektusurftranen.htm",
"timegate_uri":"http://timetravel.mementoweb.org/timegate/http://www.utc.sk/cetra/cetraen/popisprojektusurftranen.htm",
"mementos": {
"list": [
{"datetime":"2005-12-16T03:49:54Z",
"uri":"http://web.archive.org/web/20051216034954/http://www.utc.sk/cetra/CetraEn/PopisProjektuSurftranEn.htm"
},
{"datetime":"2006-01-29T07:07:01Z",
"uri":"http://web.archive.org/web/20060129070701/http://www.utc.sk/cetra/CetraEn/PopisProjektuSurftranEn.htm"
},
{"datetime":"2006-02-03T17:55:46Z",
"uri":"http://web.archive.org/web/20060203175546/http://www.utc.sk/cetra/CetraEn/PopisProjektuSurftranEn.htm"
},
{"datetime":"2006-10-03T17:19:13Z",
"uri":"http://web.archive.org/web/20061003171913/http://www.utc.sk/cetra/CetraEn/PopisProjektuSurftranEn.htm"
}
]
 },"timemap_uri": {
"json_format": "http://labs.mementoweb.org/timemap/json/1/http://www.utc.sk/cetra/cetraen/popisprojektusurftranen.htm"}
 }