{"original_uri":"http://www.e3mlab.ntua.gr/cascade.html",
"timegate_uri":"http://timetravel.mementoweb.org/timegate/http://www.e3mlab.ntua.gr/cascade.html",
"mementos": {
"list": [
{"datetime":"2006-07-21T00:32:17Z",
"uri":"http://web.archive.org/web/20060721003217/http://www.e3mlab.ntua.gr/cascade.html"
},
{"datetime":"2007-02-08T04:03:34Z",
"uri":"http://web.archive.org/web/20070208040334/http://www.e3mlab.ntua.gr/cascade.html"
},
{"datetime":"2007-04-28T10:48:41Z",
"uri":"http://web.archive.org/web/20070428104841/http://www.e3mlab.ntua.gr/cascade.html"
},
{"datetime":"2007-08-27T17:06:47Z",
"uri":"http://web.archive.org/web/20070827170647/http://www.e3mlab.ntua.gr/cascade.html"
},
{"datetime":"2011-04-16T13:48:43Z",
"uri":"http://web.archive.org/web/20110416134843/http://www.e3mlab.ntua.gr/cascade.html"
},
{"datetime":"2012-09-22T05:43:01Z",
"uri":"http://web.archive.org/web/20120922054301/http://www.e3mlab.ntua.gr/cascade.html"
},
{"datetime":"2014-02-27T03:37:55Z",
"uri":"http://web.archive.org/web/20140227033755/http://www.e3mlab.ntua.gr/cascade.html"
}
]
 },"timemap_uri": {
"json_format": "http://labs.mementoweb.org/timemap/json/1/http://www.e3mlab.ntua.gr/cascade.html"}
 }