{"original_uri":"http://www.ims.demokritos.gr/ET4US/index.htm",
"timegate_uri":"http://timetravel.mementoweb.org/timegate/http://www.ims.demokritos.gr/ET4US/index.htm",
"mementos": {
"list": [
{"datetime":"2005-04-26T19:49:11Z",
"uri":"http://web.archive.org/web/20050426194911/http://www.ims.demokritos.gr/ET4US/index.htm"
},
{"datetime":"2007-05-09T20:01:54Z",
"uri":"http://web.archive.org/web/20070509200154/http://www.ims.demokritos.gr/ET4US/index.htm"
},
{"datetime":"2010-03-05T11:10:26Z",
"uri":"http://web.archive.org/web/20100305111026/http://www.ims.demokritos.gr/ET4US/index.htm"
}
]
 },"timemap_uri": {
"json_format": "http://labs.mementoweb.org/timemap/json/1/http://www.ims.demokritos.gr/ET4US/index.htm"}
 }