{"original_uri":"http://arch.her.hcmr.gr/enviefh/",
"timegate_uri":"http://timetravel.mementoweb.org/timegate/http://arch.her.hcmr.gr/enviefh/",
"mementos": {
"list": [
{"datetime":"2007-12-12T04:53:27Z",
"uri":"http://web.archive.org/web/20071212045327/http://arch.her.hcmr.gr/enviefh"
},
{"datetime":"2007-12-12T04:53:49Z",
"uri":"http://web.archive.org/web/20071212045349/http://arch.her.hcmr.gr/enviefh/"
},
{"datetime":"2009-02-15T01:53:17Z",
"uri":"http://web.archive.org/web/20090215015317/http://arch.her.hcmr.gr/enviefh/"
},
{"datetime":"2015-02-24T01:27:43Z",
"uri":"http://web.archive.org/web/20150224012743/http://arch.her.hcmr.gr/enviefh/"
}
]
 },"timemap_uri": {
"json_format": "http://labs.mementoweb.org/timemap/json/1/http://arch.her.hcmr.gr/enviefh/"}
 }