{"original_uri":"http://wisecare.dn.uoa.gr/",
"timegate_uri":"http://timetravel.mementoweb.org/timegate/http://wisecare.dn.uoa.gr/",
"mementos": {
"list": [
{"datetime":"1999-01-25T09:27:49Z",
"uri":"http://web.archive.org/web/19990125092749/http://wisecare.dn.uoa.gr/"
},
{"datetime":"1999-02-08T01:09:31Z",
"uri":"http://web.archive.org/web/19990208010931/http://wisecare.dn.uoa.gr/"
},
{"datetime":"1999-10-11T17:32:36Z",
"uri":"http://web.archive.org/web/19991011173236/http://wisecare.dn.uoa.gr/"
},
{"datetime":"2000-04-21T20:44:23Z",
"uri":"http://web.archive.org/web/20000421204423/http://wisecare.dn.uoa.gr/"
},
{"datetime":"2000-05-03T16:30:17Z",
"uri":"http://web.archive.org/web/20000503163017/http://wisecare.dn.uoa.gr/"
},
{"datetime":"2000-06-07T13:50:17Z",
"uri":"http://web.archive.org/web/20000607135017/http://wisecare.dn.uoa.gr/"
},
{"datetime":"2000-10-10T12:40:27Z",
"uri":"http://web.archive.org/web/20001010124027/http://wisecare.dn.uoa.gr/"
},
{"datetime":"2000-12-14T09:31:00Z",
"uri":"http://web.archive.org/web/20001214093100/http://wisecare.dn.uoa.gr/"
},
{"datetime":"2001-02-01T05:28:00Z",
"uri":"http://web.archive.org/web/20010201052800/http://wisecare.dn.uoa.gr/"
},
{"datetime":"2001-02-11T14:33:00Z",
"uri":"http://web.archive.org/web/20010211143300/http://wisecare.dn.uoa.gr/"
}
]
 },"timemap_uri": {
"json_format": "http://labs.mementoweb.org/timemap/json/1/http://wisecare.dn.uoa.gr/"}
 }