{"original_uri":"http://www.forthnet.gr/imag-arts/english/geolFrame1.htm",
"timegate_uri":"http://timetravel.mementoweb.org/timegate/http://www.forthnet.gr/imag-arts/english/geolFrame1.htm",
"mementos": {
"list": [
{"datetime":"2001-07-01T09:10:54Z",
"uri":"http://web.archive.org/web/20010701091054/http://www.forthnet.gr/imag-arts/english/geolFrame1.htm"
},
{"datetime":"2003-04-04T22:19:16Z",
"uri":"http://web.archive.org/web/20030404221916/http://www.forthnet.gr/imag-arts/english/geolFrame1.htm"
},
{"datetime":"2003-07-07T02:21:24Z",
"uri":"http://web.archive.org/web/20030707022124/http://www.forthnet.gr/imag-arts/english/geolFrame1.htm"
},
{"datetime":"2004-01-14T08:53:22Z",
"uri":"http://web.archive.org/web/20040114085322/http://www.forthnet.gr/imag-arts/english/geolFrame1.htm"
},
{"datetime":"2004-03-07T14:20:08Z",
"uri":"http://web.archive.org/web/20040307142008/http://www.forthnet.gr/imag-arts/english/geolFrame1.htm"
},
{"datetime":"2004-06-14T23:04:07Z",
"uri":"http://web.archive.org/web/20040614230407/http://www.forthnet.gr/imag-arts/english/geolFrame1.htm"
},
{"datetime":"2004-09-17T09:21:55Z",
"uri":"http://web.archive.org/web/20040917092155/http://www.forthnet.gr/imag-arts/english/geolFrame1.htm"
},
{"datetime":"2005-01-04T04:48:45Z",
"uri":"http://web.archive.org/web/20050104044845/http://www.forthnet.gr/imag-arts/english/geolFrame1.htm"
},
{"datetime":"2005-04-15T16:57:52Z",
"uri":"http://web.archive.org/web/20050415165752/http://www.forthnet.gr/imag-arts/english/geolFrame1.htm"
},
{"datetime":"2005-11-19T10:18:25Z",
"uri":"http://web.archive.org/web/20051119101825/http://www.forthnet.gr/imag-arts/english/geolFrame1.htm"
}
]
 },"timemap_uri": {
"json_format": "http://labs.mementoweb.org/timemap/json/1/http://www.forthnet.gr/imag-arts/english/geolFrame1.htm"}
 }