{"original_uri":"http://www.thessal.singular.gr/foodex",
"timegate_uri":"http://timetravel.mementoweb.org/timegate/http://www.thessal.singular.gr/foodex",
"mementos": {
"list": [
{"datetime":"1999-05-08T07:20:24Z",
"uri":"http://web.archive.org/web/19990508072024/http://www.thessal.singular.gr/foodex"
}
]
 },"timemap_uri": {
"json_format": "http://labs.mementoweb.org/timemap/json/1/http://www.thessal.singular.gr/foodex"}
 }