{"original_uri":"http://www.iesl.forth.gr/research/activity.aspx?id=47",
"timegate_uri":"http://timetravel.mementoweb.org/timegate/http://www.iesl.forth.gr/research/activity.aspx?id=47",
"mementos": {
"list": [
{"datetime":"2016-06-12T11:07:30Z",
"uri":"http://web.archive.org/web/20160612110730/http://www.iesl.forth.gr/research/activity.aspx?id=47"
}
]
 },"timemap_uri": {
"json_format": "http://labs.mementoweb.org/timemap/json/1/http://www.iesl.forth.gr/research/activity.aspx?id=47"}
 }