{"original_uri":"http://www.planet.gr/wit",
"timegate_uri":"http://timetravel.mementoweb.org/timegate/http://www.planet.gr/wit",
"mementos": {
"list": [
{"datetime":"2000-09-01T06:32:30Z",
"uri":"http://web.archive.org/web/20000901063230/http://www.planet.gr/wit"
},
{"datetime":"2000-11-15T09:00:00Z",
"uri":"http://web.archive.org/web/20001115090000/http://www.planet.gr/wit"
},
{"datetime":"2001-04-09T20:05:17Z",
"uri":"http://web.archive.org/web/20010409200517/http://www.planet.gr/wit"
},
{"datetime":"2001-06-18T10:44:44Z",
"uri":"http://web.archive.org/web/20010618104444/http://www.planet.gr/wit"
},
{"datetime":"2002-08-18T07:51:35Z",
"uri":"http://web.archive.org/web/20020818075135/http://www.planet.gr/wit"
},
{"datetime":"2002-12-21T20:57:23Z",
"uri":"http://web.archive.org/web/20021221205723/http://www.planet.gr/wit"
},
{"datetime":"2003-02-27T12:43:37Z",
"uri":"http://web.archive.org/web/20030227124337/http://www.planet.gr/wit"
},
{"datetime":"2003-06-28T05:15:18Z",
"uri":"http://web.archive.org/web/20030628051518/http://www.planet.gr/wit"
},
{"datetime":"2003-08-03T13:20:37Z",
"uri":"http://web.archive.org/web/20030803132037/http://www.planet.gr/wit"
},
{"datetime":"2004-10-22T03:06:27Z",
"uri":"http://web.archive.org/web/20041022030627/http://www.planet.gr/wit"
},
{"datetime":"2004-12-11T05:58:22Z",
"uri":"http://web.archive.org/web/20041211055822/http://www.planet.gr/wit"
},
{"datetime":"2005-03-07T22:53:51Z",
"uri":"http://web.archive.org/web/20050307225351/http://www.planet.gr/wit"
}
]
 },"timemap_uri": {
"json_format": "http://labs.mementoweb.org/timemap/json/1/http://www.planet.gr/wit"}
 }