{"original_uri":"http://www.tol.hol.gr/business/effect",
"timegate_uri":"http://timetravel.mementoweb.org/timegate/http://www.tol.hol.gr/business/effect",
"mementos": {
"list": [
{"datetime":"1997-10-25T21:35:42Z",
"uri":"http://web.archive.org/web/19971025213542/http://www.tol.hol.gr/business/effect/"
},
{"datetime":"1998-01-19T07:43:12Z",
"uri":"http://web.archive.org/web/19980119074312/http://www.tol.hol.gr/business/effect/"
},
{"datetime":"1998-12-01T20:41:58Z",
"uri":"http://web.archive.org/web/19981201204158/http://www.tol.hol.gr/business/effect"
},
{"datetime":"1999-02-19T16:06:30Z",
"uri":"http://web.archive.org/web/19990219160630/http://www.tol.hol.gr/business/effect"
},
{"datetime":"1999-02-19T18:22:43Z",
"uri":"http://web.archive.org/web/19990219182243/http://www.tol.hol.gr/business/effect/"
},
{"datetime":"1999-04-23T07:00:17Z",
"uri":"http://web.archive.org/web/19990423070017/http://www.tol.hol.gr/business/effect"
},
{"datetime":"1999-04-29T15:28:59Z",
"uri":"http://web.archive.org/web/19990429152859/http://www.tol.hol.gr/business/effect"
},
{"datetime":"2000-04-25T03:00:59Z",
"uri":"http://web.archive.org/web/20000425030059/http://www.tol.hol.gr/business/effect"
},
{"datetime":"2000-05-05T23:12:16Z",
"uri":"http://web.archive.org/web/20000505231216/http://www.tol.hol.gr/business/effect"
},
{"datetime":"2000-05-20T01:37:41Z",
"uri":"http://web.archive.org/web/20000520013741/http://www.tol.hol.gr/business/effect"
},
{"datetime":"2000-10-20T09:20:28Z",
"uri":"http://web.archive.org/web/20001020092028/http://www.tol.hol.gr/business/effect"
}
]
 },"timemap_uri": {
"json_format": "http://labs.mementoweb.org/timemap/json/1/http://www.tol.hol.gr/business/effect"}
 }